### ISSUE TITLE
Serialization error when item contains timezone-aware datetime object

### ISSUE THREAD

**Issue by redapple** [scrapinghub/python-scrapinghub#80]
When using dateparser>=0.6, the parser produces timezone-aware datetime objects if there's a timezone in the input string.

Example spider:

```
# -*- coding: utf-8 -*-
from datetime import datetime

import scrapy
import dateparser



class ExampleSpider(scrapy.Spider):
    name = 'example'
    allowed_domains = ['example.com']
    start_urls = ['http://example.com/']

    def parse(self, response):
        return {'url': response.url,
                'ts': dateparser.parse(
                        datetime.utcnow().isoformat()+'Z')}
```

Error seen on Scrapy Cloud:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/lib/python3.6/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/usr/local/lib/python3.6/site-packages/sh_scrapy/extension.py", line 47, in item_scraped
    self._write_item(item)
  File "/usr/local/lib/python3.6/site-packages/sh_scrapy/writer.py", line 78, in write_item
    self._write('ITM', item)
  File "/usr/local/lib/python3.6/site-packages/sh_scrapy/writer.py", line 46, in _write
    default=jsondefault
  File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/site-packages/scrapinghub/hubstorage/serialization.py", line 43, in jsondefault
    delta = o - EPOCH
TypeError: can't subtract offset-naive and offset-aware datetimes
```

**Comment by dangra** [comment]
fixed by #82
