### ISSUE TITLE
Getting multiple errors in app console on executing scraper

### ISSUE THREAD

**Issue by Wineartist** [scrapinghub/python-scrapinghub#83]
Hi,

I have added a scraper and added it in scrapinghub. After executing the scraper I can see an entry of my job id in completed jobs section. The error column in the **completed jobs section is showing  2 errors**.
On checking job log I got error details which is added below.

**Error 1**

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/usr/local/lib/python2.7/site-packages/scrapy/extensions/feedexport.py", line 185, in open_spider
    uri = self.urifmt % self._get_uri_params(spider)
KeyError: 'date'`

**Error 2**

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/usr/local/lib/python2.7/site-packages/scrapy/extensions/feedexport.py", line 210, in item_scraped
    slot = self.slot
AttributeError: 'FeedExporter' object has no attribute 'slot'`

Please let me know if there is any fix for this.

Thanks in advance.

**Comment by vshlapakov** [comment]
Hi @Wineartist, it doesn't look related with the `python-scrapinghub` package at all, I'm closing this issue. 

My blind guess that 1st error is likely related with wrong `FEED_URI` setting having `%(date)s` param inside while [get_uri_params()](https://github.com/scrapy/scrapy/blob/1.1/scrapy/extensions/feedexport.py#L249) response dict doesn't have such field - so the `date` field should be removed from `FEED_URI` or spider should have a corresponding attribute. And 2nd error is just a consequence of 1st one due to misconfigured feed exporter, see https://github.com/scrapy/scrapy/issues/2518.

If there're other questions, please ping Scrapinghub support or ask in Scrapy project tracker itself.
